package cog.fsd.java.assgn2.dto;

// default package
// Generated Jun 29, 2019, 10:55:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CogSubject generated by hbm2java
 */
public class Subject implements java.io.Serializable { 

	private int id;
	private String subtitle;
	private Integer duration;
	private Set<Book> cogBooks = new HashSet<Book>(0);

	public Subject() {
	}

	public Subject(int id) {
		this.id = id;
	}

	public Subject(int id, String subtitle, Integer duration, Set<Book> cogBooks) {
		this.id = id;
		this.subtitle = subtitle;
		this.duration = duration;
		this.cogBooks = cogBooks;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSubtitle() {
		return this.subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Set<Book> getCogBooks() {
		return this.cogBooks;
	}

	public void setCogBooks(Set<Book> cogBooks) {
		this.cogBooks = cogBooks;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("subjectId:").append(id).append(",").append("subtile : ").append(subtitle);
		return sb.toString();
		
	}
}
